services:
  java_app:
    container_name: java.app
    image: appimage
    build: .
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      java_db:
        condition: service_healthy
    volumes:
      - images_data:/app/fotos
  java_db:
    container_name: java_db
    image: mysql:8.0
    ports:
      - "3306:3306"
    env_file:
      - .env
    volumes:
      - db_data:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "java_db" ]
      interval: 30s
      timeout: 10s
      retries: 5
      start_period: 30s
volumes:
  db_data:
  images_data: